# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       gummiboot

# >> macros
# << macros

Summary:    Simple EFI Boot Manager
Version:    45
Release:    1
Group:      System/Boot
License:    LGPL-2.1
ExclusiveArch:  %ix86 x86_64
URL:        http://cgit.freedesktop.org/gummiboot/
Source0:    %{name}-%{version}.tar.xz
Source100:  gummiboot.yaml
BuildRequires:  pkgconfig(blkid)
BuildRequires:  gnu-efi

%description
gummiboot is a simple UEFI boot manager which executes configured EFI
images. The default entry is selected by a configured pattern (glob)
or an on-screen menu.

gummiboot operates on the EFI System Partition (ESP) only. gummiboot
reads simple and entirely generic boot loader configuration files;
one file per boot loader entry to select from.

Configuration file fragments, kernels, initrds, other EFI images need
to reside on the ESP.


%package splash
Summary:    Gummiboot default splash image
Group:      System/Boot
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}

%description splash
This package contains the Gummiboot default splash image. It's the
project logo and maintained in the upstream gummiboot Git tree.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%reconfigure --libexecdir=%{_prefix}/lib
make V=1 %{?_smp_mflags}
# << build pre



# >> build post
#mv gummiboot%{machine_type_name}.efi gummiboot%{machine_type_name}.orig
#%pesign -s -i gummiboot%{machine_type_name}.orig -o gummiboot%{machine_type_name}.efi
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
# << install post

%post
# >> post
/usr/bin/gummiboot update >/dev/null 2>&1 || :
# << post

%files
%defattr(-,root,root,-)
%doc README LICENSE
%{_bindir}/gummiboot
%dir %{_prefix}/lib/gummiboot
%{_prefix}/lib/gummiboot/gummiboot*.efi
# >> files
# << files

%files splash
%defattr(-,root,root,-)
%{_datadir}/%{name}/splash.bmp
# >> files splash
# << files splash
