# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       gummiboot

# >> macros
# << macros

Summary:    EFI Kernel loader
Version:    45
Release:    1
Group:      System/Boot
License:    LGPL-2.1
ExclusiveArch:  %ix86 x86_64
URL:        http://cgit.freedesktop.org/gummiboot/
Source0:    %{name}-%{version}.tar.xz
Source100:  gummiboot.yaml
BuildRequires:  pkgconfig(blkid)
BuildRequires:  gnu-efi

%description
Gummiboot is a simple EFI bootloader.

%package splash
Summary:    Gummiboot default splash image
Group:      System/Boot
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}

%description splash
This package contains the Gummiboot default splash image. It's the
project logo and maintained in the upstream gummiboot Git tree.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --with-efi-libdir=%{_libdir} \
    --with-efi-ldsdir=%{_libdir}

make

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/gummiboot
%{_libdir}/gummiboot/gummiboot*.efi
# >> files
# << files

%files splash
%defattr(-,root,root,-)
%{_datadir}/%{name}/splash.bmp
# >> files splash
# << files splash
